name: Linters

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  linters:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']

    steps:
    - name: Invoke linter hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.SHIFT_URL }}
        data: '{ "code": "LF" }'
